sql_links_daily = """select 
  date, LC029__SUCCESSFUL_LOYALTY_CARD_JOINS__DAILY_CHANNEL_BRAND_RETAILER__PIT from
  METRICS.LOYALTY_CARDS.LC__LINKS_JOINS__DAILY_RETAILER_CHANNEL"""

sql_joins_daily = """select 
  date, LC025__SUCCESSFUL_LOYALTY_CARD_LINKS__DAILY_CHANNEL_BRAND_RETAILER__PIT from
  METRICS.LOYALTY_CARDS.LC__LINKS_JOINS__DAILY_RETAILER_CHANNEL"""

sql_combine_lc_daily = """select 
  date, LC031__FAILED_LOYALTY_CARD_JOINS__DAILY_CHANNEL_BRAND_RETAILER__PIT as FAILED"""
